KeysDictionary("arcticfilterwheel", (1,0), *(
    Key("text",
        String(),
        help = "Text message",
    ),
    Key("yourUserID",
        Int(),
        help = "Your user ID number; use this to recognize replies triggered by your commands; never 0",
    ),
    Key("numUsers",
        Int(),
        help = "Number of connected users",
    ),
    Key("userInfo",
        Int(help = "user ID"),
        String(help = "socket address"),
        help = "Basic information about one user",
    ),
    Key("unknownCommand",
        String(help = "command verb"),
        help = "The command verb (the first word of your command string) is not supported by this actor",
    ),
    Key("version",
        String(invalid="?"),
        help = "The version of the actor",
    ),
    Key("refCount",
        Int(help = "refcount"),
        String(help = "object"),
        help = "The reference count for an object",
    ),
    Key("wheelID",
        Int(help = "wheel id"),
        help = "The integer ID for the wheel currently loaded.  0 indicates no wheel loaded."
    ),
    Key("filterID",
        Int(help = "filter id", invalid="NaN"),
        help = "The integer ID for the current filter position of the filter wheel (1-6 allowed)"
    ),
    Key("hall",
        String(invalid="?", help = "hall effect"),
        help = "Hall effect value."
    ),
    Key("cmdFilterID",
        Int(invalid = "NaN"),
        help = "The integer ID for the commanded filter filter position of the filter wheel (1-6 allowed)"
    ),
    Key("encoderPos",
        Int(help = "endoder position", invalid="NaN"),
        help = "The current value reported by the encoder"
    ),
    Key("desiredStep",
        Int(invalid="NaN"),
        help = "The desired motor step position"
    ),
    Key("currentStep",
        Int(invalid="NaN"),
        help = "The current step position of the motor"
    ),
    Key("state",
        String(),
        help = "The state of the filter wheel one of: NotHomed, Homing, Moving, Done"
    ),
    # Key("isMoving",
    #     Bool(0, 1),
    #     help = "is the filter wheel moving"
    # ),
    # Key("isHomed",
    #     Bool(0, 1),
    #     help = "is the filter wheel homed"
    # ),
    # Key("isHoming",
    #     Bool(0, 1),
    #     help = "is the filter wheel currently"
    # ),
))
